---
version: 2
jobs:
  build:
    docker:
      - image: 'kmkfw/base'

    environment:
      KMK_TEST: 1

    steps:
      - checkout
      - run: make test
      - run: make dist
      - run: make dist-deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
