version: 2
jobs:
  lint:
    docker:
      - image: 'python:3.7'

    environment:
        KMK_TEST: 1
        PIPENV_VENV_IN_PROJECT: 1

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-kmk-lint-{{ checksum "Pipfile.lock" }}

      - run: pip install pipenv==2018.7.1
      - run: pipenv install --dev
      - run: pipenv run flake8

      - save_cache:
          key: v1-kmk-lint-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv

workflows:
  version: 2
  build-deploy:
    jobs:
      - lint:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
