name: Deploy

on:
  push:
    branches: [ master ]
  create:
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: kmkfw/base

    steps:
      - uses: actions/checkout@v2
      - run: make test
      - run: make dist
        
      - run: make dist-deploy
        if: github.event_name == 'push'
        env:
          CIRCLE_BRANCH: ${{GITHUB_REF_NAME}}
      - run: make dist-deploy
        if: github.event_name == 'create'
        env:
          CIRCLE_TAG: ${{GITHUB_REF_NAME}}
